# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'device_installer.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(679, 481)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_update_drivers = QtWidgets.QPushButton(Form)
        self.pushButton_update_drivers.setEnabled(True)
        self.pushButton_update_drivers.setObjectName("pushButton_update_drivers")
        self.gridLayout.addWidget(self.pushButton_update_drivers, 2, 2, 1, 1)
        self.textEdit_device_info = QtWidgets.QTextEdit(Form)
        self.textEdit_device_info.setEnabled(True)
        self.textEdit_device_info.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit_device_info.setObjectName("textEdit_device_info")
        self.gridLayout.addWidget(self.textEdit_device_info, 4, 2, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setEnabled(True)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 3, 2, 1, 1)
        self.pushButton_install_update_selected = QtWidgets.QPushButton(Form)
        self.pushButton_install_update_selected.setEnabled(True)
        self.pushButton_install_update_selected.setObjectName("pushButton_install_update_selected")
        self.gridLayout.addWidget(self.pushButton_install_update_selected, 0, 2, 1, 1)
        self.pushButton_uninstall = QtWidgets.QPushButton(Form)
        self.pushButton_uninstall.setEnabled(True)
        self.pushButton_uninstall.setObjectName("pushButton_uninstall")
        self.gridLayout.addWidget(self.pushButton_uninstall, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_search_name = QtWidgets.QLineEdit(Form)
        self.lineEdit_search_name.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_search_name.setObjectName("lineEdit_search_name")
        self.gridLayout.addWidget(self.lineEdit_search_name, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_search_tags = QtWidgets.QLineEdit(Form)
        self.lineEdit_search_tags.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_search_tags.setObjectName("lineEdit_search_tags")
        self.gridLayout.addWidget(self.lineEdit_search_tags, 1, 1, 1, 1)
        self.pushButton_sel_all = QtWidgets.QPushButton(Form)
        self.pushButton_sel_all.setObjectName("pushButton_sel_all")
        self.gridLayout.addWidget(self.pushButton_sel_all, 2, 0, 1, 1)
        self.pushButton_sel_none = QtWidgets.QPushButton(Form)
        self.pushButton_sel_none.setObjectName("pushButton_sel_none")
        self.gridLayout.addWidget(self.pushButton_sel_none, 2, 1, 1, 1)
        self.device_table = QtWidgets.QTableWidget(Form)
        self.device_table.setObjectName("device_table")
        self.device_table.setColumnCount(0)
        self.device_table.setRowCount(0)
        self.gridLayout.addWidget(self.device_table, 3, 0, 2, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_update_drivers.setText(_translate("Form", "Update all installed drivers"))
        self.pushButton_install_update_selected.setText(_translate("Form", "Install / Update Selected"))
        self.pushButton_uninstall.setText(_translate("Form", "Uninstall Selected"))
        self.label.setText(_translate("Form", "Search name:"))
        self.lineEdit_search_name.setPlaceholderText(_translate("Form", "device name"))
        self.label_2.setText(_translate("Form", "Search tags:"))
        self.lineEdit_search_tags.setPlaceholderText(_translate("Form", "tags"))
        self.pushButton_sel_all.setText(_translate("Form", "Select All"))
        self.pushButton_sel_none.setText(_translate("Form", "Select None"))
