# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'general_protocol_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Protocol_Settings(object):
    def setupUi(self, Protocol_Settings):
        Protocol_Settings.setObjectName("Protocol_Settings")
        Protocol_Settings.resize(397, 668)
        self.gridLayout = QtWidgets.QGridLayout(Protocol_Settings)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_2 = QtWidgets.QWidget(Protocol_Settings)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout.addWidget(self.widget_2, 4, 0, 1, 1)
        self.label_title = QtWidgets.QLabel(Protocol_Settings)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.gridLayout.addWidget(self.label_title, 0, 0, 1, 2)
        self.tableView_variables = QtWidgets.QTableView(Protocol_Settings)
        self.tableView_variables.setObjectName("tableView_variables")
        self.tableView_variables.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.tableView_variables, 6, 0, 1, 4)
        self.lineEdit_protocol_name = QtWidgets.QLineEdit(Protocol_Settings)
        self.lineEdit_protocol_name.setObjectName("lineEdit_protocol_name")
        self.gridLayout.addWidget(self.lineEdit_protocol_name, 1, 1, 1, 3)
        self.label_4 = QtWidgets.QLabel(Protocol_Settings)
        self.label_4.setMaximumSize(QtCore.QSize(85, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.lineEdit_filename = QtWidgets.QLineEdit(Protocol_Settings)
        self.lineEdit_filename.setObjectName("lineEdit_filename")
        self.gridLayout.addWidget(self.lineEdit_filename, 2, 1, 1, 3)
        self.pushButton_remove_variable = QtWidgets.QPushButton(Protocol_Settings)
        self.pushButton_remove_variable.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_remove_variable.setObjectName("pushButton_remove_variable")
        self.gridLayout.addWidget(self.pushButton_remove_variable, 5, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(Protocol_Settings)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(Protocol_Settings)
        self.label.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.pushButton_add_variable = QtWidgets.QPushButton(Protocol_Settings)
        self.pushButton_add_variable.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_add_variable.setObjectName("pushButton_add_variable")
        self.gridLayout.addWidget(self.pushButton_add_variable, 5, 2, 1, 1)
        self.widget = QtWidgets.QWidget(Protocol_Settings)
        self.widget.setObjectName("widget")
        self.gridLayout.addWidget(self.widget, 3, 0, 1, 1)

        self.retranslateUi(Protocol_Settings)
        QtCore.QMetaObject.connectSlotsByName(Protocol_Settings)

    def retranslateUi(self, Protocol_Settings):
        _translate = QtCore.QCoreApplication.translate
        Protocol_Settings.setWindowTitle(_translate("Protocol_Settings", "Form"))
        self.label_title.setText(_translate("Protocol_Settings", "General Configuration"))
        self.label_4.setText(_translate("Protocol_Settings", "Protocol Name:"))
        self.lineEdit_filename.setText(_translate("Protocol_Settings", "Datafile"))
        self.lineEdit_filename.setPlaceholderText(_translate("Protocol_Settings", "Filename"))
        self.pushButton_remove_variable.setText(_translate("Protocol_Settings", "-"))
        self.label_2.setText(_translate("Protocol_Settings", "Variables"))
        self.label.setText(_translate("Protocol_Settings", "Filename:"))
        self.pushButton_add_variable.setText(_translate("Protocol_Settings", "+"))
