# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'instrument_config.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(483, 231)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(9, 9, 9, 9)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_config = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_config.setFont(font)
        self.label_config.setObjectName("label_config")
        self.gridLayout.addWidget(self.label_config, 0, 3, 1, 2)
        self.pushButton_add = QtWidgets.QPushButton(Form)
        self.pushButton_add.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setObjectName("pushButton_add")
        self.gridLayout.addWidget(self.pushButton_add, 1, 3, 1, 1)
        self.tableWidget_instruments = QtWidgets.QTableWidget(Form)
        self.tableWidget_instruments.setObjectName("tableWidget_instruments")
        self.tableWidget_instruments.setColumnCount(0)
        self.tableWidget_instruments.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget_instruments, 1, 0, 2, 2)
        self.lineEdit_search = QtWidgets.QLineEdit(Form)
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.gridLayout.addWidget(self.lineEdit_search, 0, 1, 1, 1)
        self.pushButton_remove = QtWidgets.QPushButton(Form)
        self.pushButton_remove.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_remove.setFont(font)
        self.pushButton_remove.setObjectName("pushButton_remove")
        self.gridLayout.addWidget(self.pushButton_remove, 1, 4, 1, 1)
        self.config_tabs = QtWidgets.QTabWidget(Form)
        self.config_tabs.setObjectName("config_tabs")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.config_widge = QtWidgets.QLabel(self.tab)
        self.config_widge.setObjectName("config_widge")
        self.gridLayout_2.addWidget(self.config_widge, 0, 0, 1, 1)
        self.config_tabs.addTab(self.tab, "")
        self.gridLayout.addWidget(self.config_tabs, 2, 3, 1, 2)

        self.retranslateUi(Form)
        self.config_tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Search name:"))
        self.label_config.setText(_translate("Form", "Configure:"))
        self.pushButton_add.setText(_translate("Form", "+"))
        self.lineEdit_search.setPlaceholderText(_translate("Form", "Search"))
        self.pushButton_remove.setText(_translate("Form", "-"))
        self.config_widge.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Select an instrument</span></p></body></html>"))
        self.config_tabs.setTabText(self.config_tabs.indexOf(self.tab), _translate("Form", "Select an instrument"))
