# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pass_ask.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Pass_Ask(object):
    def setupUi(self, Pass_Ask):
        Pass_Ask.setObjectName("Pass_Ask")
        Pass_Ask.resize(400, 106)
        self.gridLayout = QtWidgets.QGridLayout(Pass_Ask)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(Pass_Ask)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_password_1 = QtWidgets.QLineEdit(Pass_Ask)
        self.lineEdit_password_1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password_1.setObjectName("lineEdit_password_1")
        self.gridLayout.addWidget(self.lineEdit_password_1, 1, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Pass_Ask)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 2)
        self.label = QtWidgets.QLabel(Pass_Ask)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)

        self.retranslateUi(Pass_Ask)
        self.buttonBox.accepted.connect(Pass_Ask.accept) # type: ignore
        self.buttonBox.rejected.connect(Pass_Ask.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Pass_Ask)

    def retranslateUi(self, Pass_Ask):
        _translate = QtCore.QCoreApplication.translate
        Pass_Ask.setWindowTitle(_translate("Pass_Ask", "Dialog"))
        self.label_2.setText(_translate("Pass_Ask", "Password:"))
        self.label.setText(_translate("Pass_Ask", "Enter sudo-password for the Ubuntu-user \"epics\":"))
