# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'read_channels.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_read_channels_config(object):
    def setupUi(self, read_channels_config):
        read_channels_config.setObjectName("read_channels_config")
        read_channels_config.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(read_channels_config)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_read_all = QtWidgets.QCheckBox(read_channels_config)
        self.checkBox_read_all.setObjectName("checkBox_read_all")
        self.gridLayout.addWidget(self.checkBox_read_all, 0, 0, 1, 1)
        self.checkBox_split_trigger = QtWidgets.QCheckBox(read_channels_config)
        self.checkBox_split_trigger.setObjectName("checkBox_split_trigger")
        self.gridLayout.addWidget(self.checkBox_split_trigger, 0, 1, 1, 1)

        self.retranslateUi(read_channels_config)
        QtCore.QMetaObject.connectSlotsByName(read_channels_config)

    def retranslateUi(self, read_channels_config):
        _translate = QtCore.QCoreApplication.translate
        read_channels_config.setWindowTitle(_translate("read_channels_config", "Form"))
        self.checkBox_read_all.setText(_translate("read_channels_config", "Read All"))
        self.checkBox_split_trigger.setText(_translate("read_channels_config", "Split trigger and read"))
