title: NOMAD-CAMELS
description: NOMAD-CAMELS
theme: just-the-docs

url: https://fau-lap.github.io/NOMAD-CAMELS

#logo: "/assets/camels_horizontal.png"
favicon_ico: "/assets/CAMELS.ico"
color_scheme: dark

# External navigation links
nav_external_links:
  - title: CAMELS on GitHub
    url: https://github.com/FAU-LAP/CAMELS
    hide_icon: false # set to true to hide the external link icon - defaults to false
  - title: NOMAD Website
    url: https://nomad-lab.eu/nomad-lab/
    hide_icon: false # set to true to hide the external link icon - defaults to false
  - title: FAIRmat Website
    url: https://www.fairmat-nfdi.eu/fairmat
    hide_icon: false # set to true to hide the external link icon - defaults to false


# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Show this page on GitHub."
gh_edit_repository: "https://github.com/FAU-LAP/CAMELS" # the github URL for your repo
gh_edit_branch: "documentation" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
