# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bruker_magnet_ni_daq_config.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_bruker_magnet_config(object):
    def setupUi(self, bruker_magnet_config):
        bruker_magnet_config.setObjectName("bruker_magnet_config")
        bruker_magnet_config.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(bruker_magnet_config)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(bruker_magnet_config)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(bruker_magnet_config)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.lineEdit_wait_time = QtWidgets.QLineEdit(bruker_magnet_config)
        self.lineEdit_wait_time.setObjectName("lineEdit_wait_time")
        self.gridLayout.addWidget(self.lineEdit_wait_time, 4, 3, 1, 1)
        self.lineEdit_reverse_time = QtWidgets.QLineEdit(bruker_magnet_config)
        self.lineEdit_reverse_time.setObjectName("lineEdit_reverse_time")
        self.gridLayout.addWidget(self.lineEdit_reverse_time, 4, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 1, 1, 1)
        self.lineEdit_power_on = QtWidgets.QLineEdit(bruker_magnet_config)
        self.lineEdit_power_on.setObjectName("lineEdit_power_on")
        self.gridLayout.addWidget(self.lineEdit_power_on, 1, 1, 1, 1)
        self.lineEdit_power_read = QtWidgets.QLineEdit(bruker_magnet_config)
        self.lineEdit_power_read.setObjectName("lineEdit_power_read")
        self.gridLayout.addWidget(self.lineEdit_power_read, 1, 3, 1, 1)
        self.lineEdit_polarity = QtWidgets.QLineEdit(bruker_magnet_config)
        self.lineEdit_polarity.setObjectName("lineEdit_polarity")
        self.gridLayout.addWidget(self.lineEdit_polarity, 2, 3, 1, 1)
        self.lineEdit_reverse = QtWidgets.QLineEdit(bruker_magnet_config)
        self.lineEdit_reverse.setObjectName("lineEdit_reverse")
        self.gridLayout.addWidget(self.lineEdit_reverse, 3, 1, 1, 1)
        self.lineEdit_power_off = QtWidgets.QLineEdit(bruker_magnet_config)
        self.lineEdit_power_off.setObjectName("lineEdit_power_off")
        self.gridLayout.addWidget(self.lineEdit_power_off, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(bruker_magnet_config)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(bruker_magnet_config)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(bruker_magnet_config)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(bruker_magnet_config)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(bruker_magnet_config)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)

        self.retranslateUi(bruker_magnet_config)
        QtCore.QMetaObject.connectSlotsByName(bruker_magnet_config)

    def retranslateUi(self, bruker_magnet_config):
        _translate = QtCore.QCoreApplication.translate
        bruker_magnet_config.setWindowTitle(_translate("bruker_magnet_config", "Form"))
        self.label_7.setText(_translate("bruker_magnet_config", "On/Off time:"))
        self.label_6.setText(_translate("bruker_magnet_config", "Reverse time:"))
        self.label_4.setText(_translate("bruker_magnet_config", "Power off DAQ-line:"))
        self.label_2.setText(_translate("bruker_magnet_config", "Polarity read DAQ-line:"))
        self.label_3.setText(_translate("bruker_magnet_config", "Power on DAQ-line:"))
        self.label_5.setText(_translate("bruker_magnet_config", "Reverse magnet DAQ-line:"))
        self.label.setText(_translate("bruker_magnet_config", "Power read DAQ-line:"))
