# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'createTask.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateTask(object):
    def setupUi(self, CreateTask):
        CreateTask.setObjectName("CreateTask")
        CreateTask.resize(278, 106)
        self.gridLayout_2 = QtWidgets.QGridLayout(CreateTask)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_taskName = QtWidgets.QLineEdit(CreateTask)
        self.lineEdit_taskName.setObjectName("lineEdit_taskName")
        self.gridLayout.addWidget(self.lineEdit_taskName, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(CreateTask)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(CreateTask)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(CreateTask)
        self.buttonBox.accepted.connect(CreateTask.accept) # type: ignore
        self.buttonBox.rejected.connect(CreateTask.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(CreateTask)

    def retranslateUi(self, CreateTask):
        _translate = QtCore.QCoreApplication.translate
        CreateTask.setWindowTitle(_translate("CreateTask", "Dialog"))
        self.label.setText(_translate("CreateTask", "Task name:"))
