# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(982, 818)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.widget_3 = QtWidgets.QWidget(self.splitter_2)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout.setContentsMargins(9, 0, 9, 9)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox_device_preset = QtWidgets.QComboBox(self.widget_3)
        self.comboBox_device_preset.setObjectName("comboBox_device_preset")
        self.gridLayout.addWidget(self.comboBox_device_preset, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget_3)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 2)
        self.widget_9 = QtWidgets.QWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_9.sizePolicy().hasHeightForWidth())
        self.widget_9.setSizePolicy(sizePolicy)
        self.widget_9.setMinimumSize(QtCore.QSize(0, 300))
        self.widget_9.setObjectName("widget_9")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.widget_9)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.splitter = QtWidgets.QSplitter(self.widget_9)
        self.splitter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitter.setLineWidth(8)
        self.splitter.setMidLineWidth(8)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setOpaqueResize(True)
        self.splitter.setHandleWidth(5)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setMinimumSize(QtCore.QSize(0, 200))
        self.widget.setObjectName("widget")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.pushButton_remove_device = QtWidgets.QPushButton(self.widget)
        self.pushButton_remove_device.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_remove_device.setObjectName("pushButton_remove_device")
        self.gridLayout_11.addWidget(self.pushButton_remove_device, 0, 2, 1, 1)
        self.pushButton_add_device = QtWidgets.QPushButton(self.widget)
        self.pushButton_add_device.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_add_device.setObjectName("pushButton_add_device")
        self.gridLayout_11.addWidget(self.pushButton_add_device, 0, 1, 1, 1)
        self.lineEdit_device_search = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_device_search.setObjectName("lineEdit_device_search")
        self.gridLayout_11.addWidget(self.lineEdit_device_search, 0, 0, 1, 1)
        self.treeView_devices = QtWidgets.QTreeView(self.widget)
        self.treeView_devices.setObjectName("treeView_devices")
        self.gridLayout_11.addWidget(self.treeView_devices, 3, 0, 2, 3)
        self.widget_2 = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_make_EPICS_environment = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_make_EPICS_environment.setObjectName("pushButton_make_EPICS_environment")
        self.gridLayout_2.addWidget(self.pushButton_make_EPICS_environment, 0, 0, 1, 1)
        self.pushButton_show_console_output = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_show_console_output.setObjectName("pushButton_show_console_output")
        self.gridLayout_2.addWidget(self.pushButton_show_console_output, 0, 1, 1, 1)
        self.textEdit_console_output = QtWidgets.QTextEdit(self.widget_2)
        self.textEdit_console_output.setObjectName("textEdit_console_output")
        self.gridLayout_2.addWidget(self.textEdit_console_output, 2, 0, 1, 2)
        self.progressBar_devices = QtWidgets.QProgressBar(self.widget_2)
        self.progressBar_devices.setEnabled(True)
        self.progressBar_devices.setProperty("value", 100)
        self.progressBar_devices.setObjectName("progressBar_devices")
        self.gridLayout_2.addWidget(self.progressBar_devices, 1, 0, 1, 2)
        self.device_config_widget = QtWidgets.QWidget(self.splitter)
        self.device_config_widget.setObjectName("device_config_widget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.device_config_widget)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_12.addWidget(self.splitter, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_9, 2, 0, 1, 2)
        self.widget_4 = QtWidgets.QWidget(self.splitter_2)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_2 = QtWidgets.QLabel(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.comboBox_measurement_preset = QtWidgets.QComboBox(self.widget_4)
        self.comboBox_measurement_preset.setObjectName("comboBox_measurement_preset")
        self.gridLayout_4.addWidget(self.comboBox_measurement_preset, 0, 1, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.widget_4)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.splitter_3 = QtWidgets.QSplitter(self.widget_5)
        self.splitter_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitter_3.setLineWidth(10)
        self.splitter_3.setMidLineWidth(10)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.widget_6 = QtWidgets.QWidget(self.splitter_3)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_6)
        self.gridLayout_6.setContentsMargins(9, 0, 9, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.widget_10 = QtWidgets.QWidget(self.widget_6)
        self.widget_10.setObjectName("widget_10")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.widget_10)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setSpacing(0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.splitter_4 = QtWidgets.QSplitter(self.widget_10)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.widget_11 = QtWidgets.QWidget(self.splitter_4)
        self.widget_11.setObjectName("widget_11")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.widget_11)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.pushButton_add_protocol = QtWidgets.QPushButton(self.widget_11)
        self.pushButton_add_protocol.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_add_protocol.setObjectName("pushButton_add_protocol")
        self.gridLayout_13.addWidget(self.pushButton_add_protocol, 0, 1, 1, 1)
        self.pushButton_remove_protocol = QtWidgets.QPushButton(self.widget_11)
        self.pushButton_remove_protocol.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_remove_protocol.setObjectName("pushButton_remove_protocol")
        self.gridLayout_13.addWidget(self.pushButton_remove_protocol, 0, 2, 1, 1)
        self.lineEdit_protocol_search = QtWidgets.QLineEdit(self.widget_11)
        self.lineEdit_protocol_search.setObjectName("lineEdit_protocol_search")
        self.gridLayout_13.addWidget(self.lineEdit_protocol_search, 0, 0, 1, 1)
        self.listView_protocols = QtWidgets.QListView(self.widget_11)
        self.listView_protocols.setObjectName("listView_protocols")
        self.gridLayout_13.addWidget(self.listView_protocols, 1, 0, 1, 3)
        self.widget_12 = QtWidgets.QWidget(self.splitter_4)
        self.widget_12.setObjectName("widget_12")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.widget_12)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.progressBar_protocols = QtWidgets.QProgressBar(self.widget_12)
        self.progressBar_protocols.setProperty("value", 100)
        self.progressBar_protocols.setObjectName("progressBar_protocols")
        self.gridLayout_14.addWidget(self.progressBar_protocols, 1, 0, 1, 2)
        self.pushButton_build_protocol = QtWidgets.QPushButton(self.widget_12)
        self.pushButton_build_protocol.setObjectName("pushButton_build_protocol")
        self.gridLayout_14.addWidget(self.pushButton_build_protocol, 0, 0, 1, 1)
        self.pushButton_show_output_meas = QtWidgets.QPushButton(self.widget_12)
        self.pushButton_show_output_meas.setObjectName("pushButton_show_output_meas")
        self.gridLayout_14.addWidget(self.pushButton_show_output_meas, 0, 1, 1, 1)
        self.textEdit_console_output_meas = QtWidgets.QTextEdit(self.widget_12)
        self.textEdit_console_output_meas.setObjectName("textEdit_console_output_meas")
        self.gridLayout_14.addWidget(self.textEdit_console_output_meas, 2, 0, 1, 2)
        self.gridLayout_15.addWidget(self.splitter_4, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.widget_10, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 0, 0, 1, 1)
        self.pushButton_run_protocol = QtWidgets.QPushButton(self.widget_6)
        self.pushButton_run_protocol.setObjectName("pushButton_run_protocol")
        self.gridLayout_6.addWidget(self.pushButton_run_protocol, 1, 0, 1, 1)
        self.widget_7 = QtWidgets.QWidget(self.splitter_3)
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.widget_7)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.pushButton_move_step_out = QtWidgets.QPushButton(self.widget_7)
        self.pushButton_move_step_out.setObjectName("pushButton_move_step_out")
        self.gridLayout_8.addWidget(self.pushButton_move_step_out, 4, 1, 1, 1)
        self.pushButton_move_step_in = QtWidgets.QPushButton(self.widget_7)
        self.pushButton_move_step_in.setObjectName("pushButton_move_step_in")
        self.gridLayout_8.addWidget(self.pushButton_move_step_in, 3, 1, 1, 1)
        self.pushButton_move_step_up = QtWidgets.QPushButton(self.widget_7)
        self.pushButton_move_step_up.setObjectName("pushButton_move_step_up")
        self.gridLayout_8.addWidget(self.pushButton_move_step_up, 3, 0, 1, 1)
        self.pushButton_move_step_down = QtWidgets.QPushButton(self.widget_7)
        self.pushButton_move_step_down.setObjectName("pushButton_move_step_down")
        self.gridLayout_8.addWidget(self.pushButton_move_step_down, 4, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget_7)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_8.addWidget(self.label_4, 0, 0, 1, 1)
        self.treeView_protocol_sequence = QtWidgets.QTreeView(self.widget_7)
        self.treeView_protocol_sequence.setObjectName("treeView_protocol_sequence")
        self.gridLayout_8.addWidget(self.treeView_protocol_sequence, 6, 0, 1, 3)
        self.pushButton_show_protocol_settings = QtWidgets.QPushButton(self.widget_7)
        self.pushButton_show_protocol_settings.setObjectName("pushButton_show_protocol_settings")
        self.gridLayout_8.addWidget(self.pushButton_show_protocol_settings, 1, 0, 1, 3)
        self.toolButton_add_step = QtWidgets.QToolButton(self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_add_step.sizePolicy().hasHeightForWidth())
        self.toolButton_add_step.setSizePolicy(sizePolicy)
        self.toolButton_add_step.setMinimumSize(QtCore.QSize(0, 23))
        self.toolButton_add_step.setObjectName("toolButton_add_step")
        self.gridLayout_8.addWidget(self.toolButton_add_step, 3, 2, 1, 1)
        self.pushButton_remove_step = QtWidgets.QPushButton(self.widget_7)
        self.pushButton_remove_step.setObjectName("pushButton_remove_step")
        self.gridLayout_8.addWidget(self.pushButton_remove_step, 4, 2, 1, 1)
        self.widget_8 = QtWidgets.QWidget(self.splitter_3)
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget_8)
        self.gridLayout_9.setContentsMargins(0, 0, 9, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_5 = QtWidgets.QLabel(self.widget_8)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_9.addWidget(self.label_5, 0, 0, 1, 1)
        self.loopstep_configuration_widget = QtWidgets.QWidget(self.widget_8)
        self.loopstep_configuration_widget.setObjectName("loopstep_configuration_widget")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.loopstep_configuration_widget)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_9.addWidget(self.loopstep_configuration_widget, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.splitter_3, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.widget_5, 1, 0, 1, 2)
        self.gridLayout_5.addWidget(self.splitter_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 982, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuPreferences = QtWidgets.QMenu(self.menubar)
        self.menuPreferences.setObjectName("menuPreferences")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionPresets = QtWidgets.QAction(MainWindow)
        self.actionPresets.setObjectName("actionPresets")
        self.actionOptions = QtWidgets.QAction(MainWindow)
        self.actionOptions.setObjectName("actionOptions")
        self.actionSave_Device_Preset = QtWidgets.QAction(MainWindow)
        self.actionSave_Device_Preset.setObjectName("actionSave_Device_Preset")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionMeasurement_Presets = QtWidgets.QAction(MainWindow)
        self.actionMeasurement_Presets.setObjectName("actionMeasurement_Presets")
        self.actionSave_Measurement_Preset = QtWidgets.QAction(MainWindow)
        self.actionSave_Measurement_Preset.setObjectName("actionSave_Measurement_Preset")
        self.actionOpen_Backup_Device_Preset = QtWidgets.QAction(MainWindow)
        self.actionOpen_Backup_Device_Preset.setObjectName("actionOpen_Backup_Device_Preset")
        self.actionLoad_Backup_Measurement_Preset = QtWidgets.QAction(MainWindow)
        self.actionLoad_Backup_Measurement_Preset.setObjectName("actionLoad_Backup_Measurement_Preset")
        self.actionAutosave_on_closing = QtWidgets.QAction(MainWindow)
        self.actionAutosave_on_closing.setCheckable(True)
        self.actionAutosave_on_closing.setObjectName("actionAutosave_on_closing")
        self.actionDevice_Driver_Builder = QtWidgets.QAction(MainWindow)
        self.actionDevice_Driver_Builder.setObjectName("actionDevice_Driver_Builder")
        self.actionDark_Mode = QtWidgets.QAction(MainWindow)
        self.actionDark_Mode.setCheckable(True)
        self.actionDark_Mode.setObjectName("actionDark_Mode")
        self.menuFile.addAction(self.actionSave_Device_Preset)
        self.menuFile.addAction(self.actionSave_Measurement_Preset)
        self.menuFile.addAction(self.actionOpen_Backup_Device_Preset)
        self.menuFile.addAction(self.actionLoad_Backup_Measurement_Preset)
        self.menuPreferences.addAction(self.actionAutosave_on_closing)
        self.menuPreferences.addAction(self.actionDark_Mode)
        self.menuTools.addAction(self.actionDevice_Driver_Builder)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPreferences.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Device Preset:"))
        self.label_6.setText(_translate("MainWindow", "Devices"))
        self.pushButton_remove_device.setText(_translate("MainWindow", "-"))
        self.pushButton_add_device.setText(_translate("MainWindow", "+"))
        self.lineEdit_device_search.setPlaceholderText(_translate("MainWindow", "Search"))
        self.pushButton_make_EPICS_environment.setText(_translate("MainWindow", "Make EPICS IOC"))
        self.pushButton_show_console_output.setText(_translate("MainWindow", "Show console output"))
        self.label_2.setText(_translate("MainWindow", "Measurement Preset:"))
        self.pushButton_add_protocol.setText(_translate("MainWindow", "+"))
        self.pushButton_remove_protocol.setText(_translate("MainWindow", "-"))
        self.lineEdit_protocol_search.setPlaceholderText(_translate("MainWindow", "Search"))
        self.pushButton_build_protocol.setText(_translate("MainWindow", "Build Protocol"))
        self.pushButton_show_output_meas.setText(_translate("MainWindow", "Show output"))
        self.label_3.setText(_translate("MainWindow", "Protocols"))
        self.pushButton_run_protocol.setText(_translate("MainWindow", "Run selected protocol(s)"))
        self.pushButton_move_step_out.setText(_translate("MainWindow", "move out"))
        self.pushButton_move_step_in.setText(_translate("MainWindow", "move in"))
        self.pushButton_move_step_up.setText(_translate("MainWindow", "move up"))
        self.pushButton_move_step_down.setText(_translate("MainWindow", "move down"))
        self.label_4.setText(_translate("MainWindow", "Sequence"))
        self.pushButton_show_protocol_settings.setText(_translate("MainWindow", "Show General Settings"))
        self.toolButton_add_step.setText(_translate("MainWindow", "+"))
        self.pushButton_remove_step.setText(_translate("MainWindow", "-"))
        self.label_5.setText(_translate("MainWindow", "Configuration"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuPreferences.setTitle(_translate("MainWindow", "Settings"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.actionPresets.setText(_translate("MainWindow", "Device-Presets"))
        self.actionOptions.setText(_translate("MainWindow", "Options"))
        self.actionSave_Device_Preset.setText(_translate("MainWindow", "Save Device Preset"))
        self.actionLoad.setText(_translate("MainWindow", "Open"))
        self.actionMeasurement_Presets.setText(_translate("MainWindow", "Measurement-Presets"))
        self.actionSave_Measurement_Preset.setText(_translate("MainWindow", "Save Measurement Preset"))
        self.actionOpen_Backup_Device_Preset.setText(_translate("MainWindow", "Load Backup Device Preset"))
        self.actionLoad_Backup_Measurement_Preset.setText(_translate("MainWindow", "Load Backup Measurement Preset"))
        self.actionAutosave_on_closing.setText(_translate("MainWindow", "Autosave on closing"))
        self.actionDevice_Driver_Builder.setText(_translate("MainWindow", "Device Driver Builder"))
        self.actionDark_Mode.setText(_translate("MainWindow", "Dark Mode"))

