# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'taskSelector.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TaskSelector(object):
    def setupUi(self, TaskSelector):
        TaskSelector.setObjectName("TaskSelector")
        TaskSelector.resize(394, 126)
        self.gridLayout_2 = QtWidgets.QGridLayout(TaskSelector)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.taskSelectComboBox = QtWidgets.QComboBox(TaskSelector)
        self.taskSelectComboBox.setObjectName("taskSelectComboBox")
        self.gridLayout.addWidget(self.taskSelectComboBox, 0, 0, 1, 3)
        self.cancelButton = QtWidgets.QPushButton(TaskSelector)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout.addWidget(self.cancelButton, 1, 2, 1, 1)
        self.okButton = QtWidgets.QPushButton(TaskSelector)
        self.okButton.setObjectName("okButton")
        self.gridLayout.addWidget(self.okButton, 1, 0, 1, 1)
        self.newTaskButton = QtWidgets.QPushButton(TaskSelector)
        self.newTaskButton.setObjectName("newTaskButton")
        self.gridLayout.addWidget(self.newTaskButton, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(TaskSelector)
        QtCore.QMetaObject.connectSlotsByName(TaskSelector)

    def retranslateUi(self, TaskSelector):
        _translate = QtCore.QCoreApplication.translate
        TaskSelector.setWindowTitle(_translate("TaskSelector", "Dialog"))
        self.cancelButton.setText(_translate("TaskSelector", "Cancel"))
        self.okButton.setText(_translate("TaskSelector", "OK"))
        self.newTaskButton.setText(_translate("TaskSelector", "New Task"))
