# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VISA_builder.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VISA_Device_Builder(object):
    def setupUi(self, VISA_Device_Builder):
        VISA_Device_Builder.setObjectName("VISA_Device_Builder")
        VISA_Device_Builder.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(VISA_Device_Builder)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(VISA_Device_Builder)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(VISA_Device_Builder)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(VISA_Device_Builder)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(VISA_Device_Builder)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(VISA_Device_Builder)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.lineEdit_name = QtWidgets.QLineEdit(VISA_Device_Builder)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.gridLayout.addWidget(self.lineEdit_name, 0, 1, 1, 3)
        self.lineEdit_baud_rate = QtWidgets.QLineEdit(VISA_Device_Builder)
        self.lineEdit_baud_rate.setObjectName("lineEdit_baud_rate")
        self.gridLayout.addWidget(self.lineEdit_baud_rate, 4, 1, 1, 3)
        self.lineEdit_write_term = QtWidgets.QLineEdit(VISA_Device_Builder)
        self.lineEdit_write_term.setObjectName("lineEdit_write_term")
        self.gridLayout.addWidget(self.lineEdit_write_term, 3, 1, 1, 3)
        self.lineEdit_read_term = QtWidgets.QLineEdit(VISA_Device_Builder)
        self.lineEdit_read_term.setObjectName("lineEdit_read_term")
        self.gridLayout.addWidget(self.lineEdit_read_term, 2, 1, 1, 3)
        self.label_6 = QtWidgets.QLabel(VISA_Device_Builder)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.lineEdit_ophyd_name = QtWidgets.QLineEdit(VISA_Device_Builder)
        self.lineEdit_ophyd_name.setObjectName("lineEdit_ophyd_name")
        self.gridLayout.addWidget(self.lineEdit_ophyd_name, 1, 1, 1, 3)
        self.lineEdit_search_tags = QtWidgets.QLineEdit(VISA_Device_Builder)
        self.lineEdit_search_tags.setObjectName("lineEdit_search_tags")
        self.gridLayout.addWidget(self.lineEdit_search_tags, 5, 1, 1, 2)
        self.label_7 = QtWidgets.QLabel(VISA_Device_Builder)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 3, 1, 1)

        self.retranslateUi(VISA_Device_Builder)
        QtCore.QMetaObject.connectSlotsByName(VISA_Device_Builder)

    def retranslateUi(self, VISA_Device_Builder):
        _translate = QtCore.QCoreApplication.translate
        VISA_Device_Builder.setWindowTitle(_translate("VISA_Device_Builder", "Form"))
        self.label.setText(_translate("VISA_Device_Builder", "Name:"))
        self.label_4.setText(_translate("VISA_Device_Builder", "Baud-Rate:"))
        self.label_5.setText(_translate("VISA_Device_Builder", "Search-Tags:"))
        self.label_3.setText(_translate("VISA_Device_Builder", "Write-Termination:"))
        self.label_2.setText(_translate("VISA_Device_Builder", "Read-Termination:"))
        self.lineEdit_baud_rate.setText(_translate("VISA_Device_Builder", "9600"))
        self.lineEdit_write_term.setText(_translate("VISA_Device_Builder", "\\n"))
        self.lineEdit_read_term.setText(_translate("VISA_Device_Builder", "\\n"))
        self.label_6.setText(_translate("VISA_Device_Builder", "Ophyd-Class-Name:"))
        self.label_7.setText(_translate("VISA_Device_Builder", "(space-separated)"))
