title: CAMELS
description: CAMELS
theme: just-the-docs

url: https://fau-lap.github.io/CAMELS

logo: "/assets/camels-horizontal.svg"

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
