name: Run Python Tests
on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - development
      - main

jobs:
  windows_test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest-md
          pip install -r requirements-dev.txt
      - name: Lint with ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          ruff --format=github --select=E9,F63,F7,F82 --target-version=py37 .
#          # default set of ruff rules with GitHub Annotations
#          ruff --format=github --target-version=py37 .
      - name: Run tests with pytest
        run: pytest -v
#      - name: Add report to summary
#        if: always()
#        run: |
#          sed -i 's/# Test Report/# ${{ inputs.report-title }}/' report.md
#          if [ ${{ inputs.click-to-expand }} = true ]; then
#            sed -i '2i <details><summary>Click to expand!</summary>' report.md
#            sed -i '$a</details>' report.md
#          fi
#          cat report.md >> $GITHUB_STEP_SUMMARY
#        shell: bash
  ubuntu_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          sudo apt update
          sudo apt install libgl1-mesa-glx libegl1-mesa libegl1 libopengl0 libpulse0
          sudo apt install libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 x11-utils
          /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX
          pip install ruff
          pip install -r requirements-dev.txt
          export QT_DEBUG_PLUGINS=1
      - name: Lint with ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          ruff --format=github --select=E9,F63,F7,F82 --target-version=py37 .
      #          # default set of ruff rules with GitHub Annotations
      #          ruff --format=github --target-version=py37 .
      - name: Run tests with pytest
        run: pytest -v
#      - name: Add report to summary
#        if: always()
#        run: |
#          sed -i 's/# Test Report/# ${{ inputs.report-title }}/' report.md
#          if [ ${{ inputs.click-to-expand }} = true ]; then
#            sed -i '2i <details><summary>Click to expand!</summary>' report.md
#            sed -i '$a</details>' report.md
#          fi
#          cat report.md >> $GITHUB_STEP_SUMMARY
#        shell: bash
  macos_test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest-md
          pip install -r requirements-dev.txt
      - name: Lint with ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          ruff --format=github --select=E9,F63,F7,F82 --target-version=py37 .
      #          # default set of ruff rules with GitHub Annotations
      #          ruff --format=github --target-version=py37 .
      - name: Run tests with pytest
        run: pytest -v
#      - name: Add report to summary
#        if: always()
#        run: |
#          sed -i 's/# Test Report/# ${{ inputs.report-title }}/' report.md
#          if [ ${{ inputs.click-to-expand }} = true ]; then
#            sed -i '2i <details><summary>Click to expand!</summary>' report.md
#            sed -i '$a</details>' report.md
#          fi
#          cat report.md >> $GITHUB_STEP_SUMMARY
#        shell: bash
