name: Run Version Tests
on:
  push:
    branches:
      - poetry_testing
      - main
  pull_request:
    branches:
      - main

jobs:
    run_tests:
        runs-on: windows-latest
        env:
            DISPLAY: ':99.0'
        steps:
            - uses: actions/checkout@v4
            # - uses: tlambert03/setup-qt-libs@v1
            # - name: Install dependencies
            #   run: |
            #     sudo apt install libgl1 libglx-mesa0 libegl1 libopengl0 libpulse0
            - name: Install Python 3.9
              uses: actions/setup-python@v5
              with:
                python-version: '3.9'
            - name: Install Python 3.10
              uses: actions/setup-python@v5
              with:
                python-version: '3.10'
            - name: Install Python 3.11
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'
            - name: Install Python 3.12
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'
            - name: Install tox and poetry
              run: |
                python -m pip install --upgrade pip
                pip install tox
            - name: run tests with tox
              run: tox