name: Sphinx Docs
on:
  release:
    types: [published]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.

jobs:
  docs_windows_complete:
    runs-on: windows-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: documentation
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx_rtd_theme myst-parser sphinx-copybutton sphinx-tabs requests pytest pytest-qt pytest-order pytest-mock pytest-timeout nomad-camels
          python -m pip install --upgrade nomad-camels
      - name: make apidoc
        run: |
          python go_through_camels_packages.py
          python apidoc_for_camels_suitcase.py
      - name: make instrument table
        run: |
          python populate_instruments_table.py
      - name: Commit and push if changed
        run: |
          git diff
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git commit -am "Update code documentation" || true
          git push origin HEAD:documentation
      - name: Sphinx build
        run: |
          sphinx-build -b html ./docs/source/ ./docs/html_out/
      - name: Commit and push if changed
        run: |
          git diff
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git commit -am "Update code documentation" || true
          git push origin HEAD:documentation
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs/html_out'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4