# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'keysight_b2912_config.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(607, 646)
        self.label_23 = QtWidgets.QLabel(Form)
        self.label_23.setGeometry(QtCore.QRect(472, 200, 101, 16))
        self.label_23.setObjectName("label_23")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(150, 500, 100, 31))
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.comboBox_8 = QtWidgets.QComboBox(Form)
        self.comboBox_8.setGeometry(QtCore.QRect(472, 320, 69, 22))
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.checkBox_8 = QtWidgets.QCheckBox(Form)
        self.checkBox_8.setGeometry(QtCore.QRect(10, 290, 110, 17))
        self.checkBox_8.setObjectName("checkBox_8")
        self.label_22 = QtWidgets.QLabel(Form)
        self.label_22.setGeometry(QtCore.QRect(462, 580, 121, 31))
        self.label_22.setWordWrap(True)
        self.label_22.setObjectName("label_22")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(322, 200, 101, 16))
        self.label_16.setObjectName("label_16")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(330, 10, 47, 13))
        self.label_2.setObjectName("label_2")
        self.lineEdit_14 = QtWidgets.QLineEdit(Form)
        self.lineEdit_14.setGeometry(QtCore.QRect(322, 610, 113, 20))
        self.lineEdit_14.setText("")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.checkBox_6 = QtWidgets.QCheckBox(Form)
        self.checkBox_6.setGeometry(QtCore.QRect(322, 270, 110, 17))
        self.checkBox_6.setObjectName("checkBox_6")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 220, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.checkBox_13 = QtWidgets.QCheckBox(Form)
        self.checkBox_13.setGeometry(QtCore.QRect(10, 570, 140, 17))
        self.checkBox_13.setObjectName("checkBox_13")
        self.lineEdit_11 = QtWidgets.QLineEdit(Form)
        self.lineEdit_11.setGeometry(QtCore.QRect(462, 530, 113, 20))
        self.lineEdit_11.setText("")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setGeometry(QtCore.QRect(10, 90, 120, 17))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        self.checkBox.setObjectName("checkBox")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(322, 350, 31, 16))
        self.label_18.setObjectName("label_18")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(10, 430, 101, 16))
        self.label_10.setObjectName("label_10")
        self.checkBox_2 = QtWidgets.QCheckBox(Form)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 180, 140, 17))
        self.checkBox_2.setObjectName("checkBox_2")
        self.comboBox_4 = QtWidgets.QComboBox(Form)
        self.comboBox_4.setGeometry(QtCore.QRect(160, 370, 69, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(160, 350, 140, 16))
        self.label_8.setObjectName("label_8")
        self.checkBox_12 = QtWidgets.QCheckBox(Form)
        self.checkBox_12.setGeometry(QtCore.QRect(10, 490, 120, 17))
        self.checkBox_12.setObjectName("checkBox_12")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 450, 113, 20))
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_18 = QtWidgets.QLineEdit(Form)
        self.lineEdit_18.setGeometry(QtCore.QRect(322, 370, 113, 20))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_7 = QtWidgets.QLineEdit(Form)
        self.lineEdit_7.setGeometry(QtCore.QRect(150, 530, 113, 20))
        self.lineEdit_7.setText("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.comboBox_7 = QtWidgets.QComboBox(Form)
        self.comboBox_7.setGeometry(QtCore.QRect(472, 370, 69, 22))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.label_27 = QtWidgets.QLabel(Form)
        self.label_27.setGeometry(QtCore.QRect(462, 500, 100, 31))
        self.label_27.setWordWrap(True)
        self.label_27.setObjectName("label_27")
        self.label_26 = QtWidgets.QLabel(Form)
        self.label_26.setGeometry(QtCore.QRect(462, 420, 100, 31))
        self.label_26.setWordWrap(True)
        self.label_26.setObjectName("label_26")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(10, 20, 601, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.checkBox_4 = QtWidgets.QCheckBox(Form)
        self.checkBox_4.setGeometry(QtCore.QRect(322, 90, 120, 17))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_4.sizePolicy().hasHeightForWidth())
        self.checkBox_4.setSizePolicy(sizePolicy)
        self.checkBox_4.setObjectName("checkBox_4")
        self.label_28 = QtWidgets.QLabel(Form)
        self.label_28.setGeometry(QtCore.QRect(322, 430, 101, 16))
        self.label_28.setObjectName("label_28")
        self.checkBox_11 = QtWidgets.QCheckBox(Form)
        self.checkBox_11.setGeometry(QtCore.QRect(10, 410, 120, 17))
        self.checkBox_11.setObjectName("checkBox_11")
        self.lineEdit_5 = QtWidgets.QLineEdit(Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 370, 113, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_10 = QtWidgets.QLineEdit(Form)
        self.lineEdit_10.setGeometry(QtCore.QRect(322, 220, 113, 20))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 200, 101, 16))
        self.label_5.setObjectName("label_5")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(10, 590, 101, 16))
        self.label_14.setObjectName("label_14")
        self.comboBox_3 = QtWidgets.QComboBox(Form)
        self.comboBox_3.setGeometry(QtCore.QRect(160, 320, 69, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.lineEdit_13 = QtWidgets.QLineEdit(Form)
        self.lineEdit_13.setGeometry(QtCore.QRect(462, 610, 113, 20))
        self.lineEdit_13.setText("")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.checkBox_5 = QtWidgets.QCheckBox(Form)
        self.checkBox_5.setGeometry(QtCore.QRect(322, 180, 140, 17))
        self.checkBox_5.setObjectName("checkBox_5")
        self.comboBox_5 = QtWidgets.QComboBox(Form)
        self.comboBox_5.setGeometry(QtCore.QRect(422, 50, 69, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.checkBox_19 = QtWidgets.QCheckBox(Form)
        self.checkBox_19.setGeometry(QtCore.QRect(322, 290, 110, 17))
        self.checkBox_19.setObjectName("checkBox_19")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(10, 510, 101, 16))
        self.label_12.setObjectName("label_12")
        self.label_24 = QtWidgets.QLabel(Form)
        self.label_24.setGeometry(QtCore.QRect(322, 590, 101, 16))
        self.label_24.setObjectName("label_24")
        self.lineEdit_9 = QtWidgets.QLineEdit(Form)
        self.lineEdit_9.setGeometry(QtCore.QRect(150, 610, 113, 20))
        self.lineEdit_9.setText("")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(113, 30, 100, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_8 = QtWidgets.QLineEdit(Form)
        self.lineEdit_8.setGeometry(QtCore.QRect(10, 610, 113, 20))
        self.lineEdit_8.setText("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(10, 350, 31, 16))
        self.label_9.setObjectName("label_9")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(8, 50, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.checkBox_14 = QtWidgets.QCheckBox(Form)
        self.checkBox_14.setGeometry(QtCore.QRect(322, 310, 120, 17))
        self.checkBox_14.setObjectName("checkBox_14")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(11, 30, 71, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_16 = QtWidgets.QLineEdit(Form)
        self.lineEdit_16.setGeometry(QtCore.QRect(322, 450, 113, 20))
        self.lineEdit_16.setText("")
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(472, 350, 140, 16))
        self.label_19.setObjectName("label_19")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(323, 30, 71, 16))
        self.label_17.setObjectName("label_17")
        self.lineEdit_12 = QtWidgets.QLineEdit(Form)
        self.lineEdit_12.setGeometry(QtCore.QRect(472, 220, 113, 20))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(10, 220, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_25 = QtWidgets.QLabel(Form)
        self.label_25.setGeometry(QtCore.QRect(425, 30, 100, 16))
        self.label_25.setObjectName("label_25")
        self.lineEdit_17 = QtWidgets.QLineEdit(Form)
        self.lineEdit_17.setGeometry(QtCore.QRect(322, 530, 113, 20))
        self.lineEdit_17.setText("")
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.checkBox_3 = QtWidgets.QCheckBox(Form)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 270, 110, 17))
        self.checkBox_3.setObjectName("checkBox_3")
        self.comboBox_2 = QtWidgets.QComboBox(Form)
        self.comboBox_2.setGeometry(QtCore.QRect(110, 50, 69, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(150, 580, 121, 31))
        self.label_15.setWordWrap(True)
        self.label_15.setObjectName("label_15")
        self.checkBox_16 = QtWidgets.QCheckBox(Form)
        self.checkBox_16.setGeometry(QtCore.QRect(322, 570, 140, 17))
        self.checkBox_16.setObjectName("checkBox_16")
        self.checkBox_15 = QtWidgets.QCheckBox(Form)
        self.checkBox_15.setGeometry(QtCore.QRect(322, 410, 120, 17))
        self.checkBox_15.setObjectName("checkBox_15")
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setGeometry(QtCore.QRect(472, 300, 130, 16))
        self.label_20.setObjectName("label_20")
        self.checkBox_9 = QtWidgets.QCheckBox(Form)
        self.checkBox_9.setGeometry(QtCore.QRect(10, 310, 120, 17))
        self.checkBox_9.setObjectName("checkBox_9")
        self.comboBox_6 = QtWidgets.QComboBox(Form)
        self.comboBox_6.setGeometry(QtCore.QRect(320, 50, 69, 22))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 47, 13))
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(160, 200, 101, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit_6 = QtWidgets.QLineEdit(Form)
        self.lineEdit_6.setGeometry(QtCore.QRect(10, 530, 113, 20))
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.checkBox_17 = QtWidgets.QCheckBox(Form)
        self.checkBox_17.setGeometry(QtCore.QRect(322, 490, 120, 17))
        self.checkBox_17.setObjectName("checkBox_17")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(160, 300, 130, 16))
        self.label_7.setObjectName("label_7")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(150, 450, 113, 20))
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setGeometry(QtCore.QRect(322, 510, 101, 16))
        self.label_21.setObjectName("label_21")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(150, 420, 100, 31))
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.checkBox_18 = QtWidgets.QCheckBox(Form)
        self.checkBox_18.setGeometry(QtCore.QRect(472, 270, 110, 17))
        self.checkBox_18.setObjectName("checkBox_18")
        self.lineEdit_15 = QtWidgets.QLineEdit(Form)
        self.lineEdit_15.setGeometry(QtCore.QRect(462, 450, 113, 20))
        self.lineEdit_15.setText("")
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(290, 10, 20, 641))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.checkBox_10 = QtWidgets.QCheckBox(Form)
        self.checkBox_10.setGeometry(QtCore.QRect(160, 270, 110, 17))
        self.checkBox_10.setObjectName("checkBox_10")
        self.lineEdit_19 = QtWidgets.QLineEdit(Form)
        self.lineEdit_19.setGeometry(QtCore.QRect(160, 140, 113, 20))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.label_29 = QtWidgets.QLabel(Form)
        self.label_29.setGeometry(QtCore.QRect(10, 120, 101, 16))
        self.label_29.setObjectName("label_29")
        self.lineEdit_20 = QtWidgets.QLineEdit(Form)
        self.lineEdit_20.setGeometry(QtCore.QRect(10, 140, 113, 20))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.label_30 = QtWidgets.QLabel(Form)
        self.label_30.setGeometry(QtCore.QRect(160, 120, 130, 16))
        self.label_30.setObjectName("label_30")
        self.lineEdit_21 = QtWidgets.QLineEdit(Form)
        self.lineEdit_21.setGeometry(QtCore.QRect(470, 140, 113, 20))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.lineEdit_22 = QtWidgets.QLineEdit(Form)
        self.lineEdit_22.setGeometry(QtCore.QRect(320, 140, 113, 20))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.label_31 = QtWidgets.QLabel(Form)
        self.label_31.setGeometry(QtCore.QRect(470, 120, 130, 16))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(Form)
        self.label_32.setGeometry(QtCore.QRect(320, 120, 101, 16))
        self.label_32.setObjectName("label_32")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_23.setText(_translate("Form", "Voltage Compliance"))
        self.label_13.setText(_translate("Form", "Voltage Auto Range Lower Limit"))
        self.comboBox_8.setItemText(0, _translate("Form", "Normal"))
        self.comboBox_8.setItemText(1, _translate("Form", "Resolution"))
        self.comboBox_8.setItemText(2, _translate("Form", "Speed"))
        self.checkBox_8.setText(_translate("Form", "Measure Current"))
        self.label_22.setText(_translate("Form", "Resistance Auto Range Upper Limit"))
        self.label_16.setText(_translate("Form", "Current Compliance"))
        self.label_2.setText(_translate("Form", "Channel 2"))
        self.checkBox_6.setText(_translate("Form", "Measure Voltage"))
        self.lineEdit_2.setText(_translate("Form", "2"))
        self.checkBox_13.setText(_translate("Form", "Resistance Auto Range"))
        self.checkBox.setText(_translate("Form", "Source Auto Range"))
        self.label_18.setText(_translate("Form", "NPLC"))
        self.label_10.setText(_translate("Form", "Current Range"))
        self.checkBox_2.setText(_translate("Form", "Enable Output Protection"))
        self.comboBox_4.setItemText(0, _translate("Form", "Normal"))
        self.comboBox_4.setItemText(1, _translate("Form", "Resolution"))
        self.comboBox_4.setItemText(2, _translate("Form", "Speed"))
        self.label_8.setText(_translate("Form", "Current Auto Range Mode"))
        self.checkBox_12.setText(_translate("Form", "Voltage Auto Range"))
        self.lineEdit_18.setText(_translate("Form", "1"))
        self.comboBox_7.setItemText(0, _translate("Form", "Normal"))
        self.comboBox_7.setItemText(1, _translate("Form", "Resolution"))
        self.comboBox_7.setItemText(2, _translate("Form", "Speed"))
        self.label_27.setText(_translate("Form", "Voltage Auto Range Lower Limit"))
        self.label_26.setText(_translate("Form", "Current Auto Range Lower Limit"))
        self.checkBox_4.setText(_translate("Form", "Source Auto Range"))
        self.label_28.setText(_translate("Form", "Current Range"))
        self.checkBox_11.setText(_translate("Form", "Current Auto Range"))
        self.lineEdit_5.setText(_translate("Form", "1"))
        self.lineEdit_10.setText(_translate("Form", "0.001"))
        self.label_5.setText(_translate("Form", "Current Compliance"))
        self.label_14.setText(_translate("Form", "Resistance Range"))
        self.comboBox_3.setItemText(0, _translate("Form", "Normal"))
        self.comboBox_3.setItemText(1, _translate("Form", "Resolution"))
        self.comboBox_3.setItemText(2, _translate("Form", "Speed"))
        self.checkBox_5.setText(_translate("Form", "Enable Output Protection"))
        self.comboBox_5.setItemText(0, _translate("Form", "Ground"))
        self.comboBox_5.setItemText(1, _translate("Form", "Float"))
        self.checkBox_19.setText(_translate("Form", "Measure Current"))
        self.label_12.setText(_translate("Form", "Voltage Range"))
        self.label_24.setText(_translate("Form", "Resistance Range"))
        self.label_4.setText(_translate("Form", "Low Terminal State"))
        self.label_9.setText(_translate("Form", "NPLC"))
        self.comboBox.setItemText(0, _translate("Form", "Voltage"))
        self.comboBox.setItemText(1, _translate("Form", "Current"))
        self.checkBox_14.setText(_translate("Form", "Measure Resistance"))
        self.label_3.setText(_translate("Form", "Source Mode"))
        self.label_19.setText(_translate("Form", "Current Auto Range Mode"))
        self.label_17.setText(_translate("Form", "Source Mode"))
        self.lineEdit_12.setText(_translate("Form", "2"))
        self.lineEdit.setText(_translate("Form", "0.001"))
        self.label_25.setText(_translate("Form", "Low Terminal State"))
        self.checkBox_3.setText(_translate("Form", "Measure Voltage"))
        self.comboBox_2.setItemText(0, _translate("Form", "Ground"))
        self.comboBox_2.setItemText(1, _translate("Form", "Float"))
        self.label_15.setText(_translate("Form", "Resistance Auto Range Upper Limit"))
        self.checkBox_16.setText(_translate("Form", "Resistance Auto Range"))
        self.checkBox_15.setText(_translate("Form", "Current Auto Range"))
        self.label_20.setText(_translate("Form", "Voltage Auto Range Mode"))
        self.checkBox_9.setText(_translate("Form", "Measure Resistance"))
        self.comboBox_6.setItemText(0, _translate("Form", "Voltage"))
        self.comboBox_6.setItemText(1, _translate("Form", "Current"))
        self.label.setText(_translate("Form", "Channel 1"))
        self.label_6.setText(_translate("Form", "Voltage Compliance"))
        self.checkBox_17.setText(_translate("Form", "Voltage Auto Range"))
        self.label_7.setText(_translate("Form", "Voltage Auto Range Mode"))
        self.label_21.setText(_translate("Form", "Voltage Range"))
        self.label_11.setText(_translate("Form", "Current Auto Range Lower Limit"))
        self.checkBox_18.setText(_translate("Form", "4-Wire"))
        self.checkBox_10.setText(_translate("Form", "4-Wire"))
        self.lineEdit_19.setText(_translate("Form", "2"))
        self.label_29.setText(_translate("Form", "Source Range"))
        self.lineEdit_20.setText(_translate("Form", "2"))
        self.label_30.setText(_translate("Form", "Source Range Lower Limit"))
        self.lineEdit_21.setText(_translate("Form", "2"))
        self.lineEdit_22.setText(_translate("Form", "2"))
        self.label_31.setText(_translate("Form", "Source Range Lower Limit"))
        self.label_32.setText(_translate("Form", "Source Range"))

